print("Format the following values")
print("Hola Mundo → Alineado a la derecha en 20 caracteres")
print("Hola Mundo → Truncamiento en el cuarto carácter (índice 3)")
print("Hola Mundo → Alineamiento al centro en 20 caracteres con truncamiento en el segundo carácter (índice 1)")
print("150 → Formateo a 5 números enteros rellenados con ceros")
print("7887 → Formateo a 7 números enteros rellenados con espacios")
print("20.02 → Formateo a 3 números enteros y 3 números decimales")

print("Resluts: \n")
print( "{:>20}".format("Hola Mundo") )
print( "{:.3}".format("Hola Mundo") )
print( "{:^20.1}".format("Hola Mundo") )
print( "{:05d}".format(150) )
print( "{:7d}".format(7887) )
print( "{:07.3f}".format(20.02) )